pr: none
trigger:
  branches:
    include:
      - main

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-prod
  - name: appName
    value: course-survey-integration-api-prod
  - name: parametersFileName
    value: prod.parameters.json

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    path: github

  - task: Npm@1
    displayName: "Npm ci"
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "ci"

  - task: Npm@1
    displayName: "Npm build"
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "run build"

  - task: Npm@1
    displayName: "Npm test"
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "test"

  - task: Npm@1
    displayName: "Npm prune"
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: "custom"
      customCommand: "prune --omit=dev"

  - template: templates/function-app/update-function.yml@cet-iac
    parameters:
      workingDir: "$(Pipeline.Workspace)/github"
      parametersFileName: $(parametersFileName)
      appName: $(appName)
