trigger: none
pr: none

parameters:
  - name: environment
    type: string
    default: ref
    values:
      - ref
      - prod
  - name: generalParams
    type: string
    displayName: General params name (from library, <team-name>-general-params)
    default: elarande-general-params
  - name: spokeParams
    type: string
    displayName: Spoke params name (from library, <spoke-name>-<env>)
    default: elarande-spoke1-<env>
  - name: parametersFileName
    type: string
    displayName: Parameters filename (from .azure folder, <env>.parameters.json)
    default: <env>.parameters.json

variables:
  - group: ${{ parameters.generalParams }}
  - group: ${{ parameters.spokeParams }}

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/cosmosdb/infra.yml@cet-iac
    parameters:
      location: $(location)
      parametersFileName: ${{ parameters.environment }}.parameters.cosmosdb.json

  - template: templates/redis/infra.yml@cet-iac
    parameters:
      location: $(location)
      environment: ${{ parameters.environment }}
      parametersFileName: ${{ parameters.environment }}.parameters.redis.json
      
  - template: templates/function-app/infra.yml@cet-iac
    parameters:
      location: $(location)
      parametersFileName: ${{ parameters.parametersFileName }}